### ISSUE TITLE
not Working in IE : 

### ISSUE THREAD

**Issue by tanveer12332** [Gix075/jqueryIntroLoader#6]
Unable to get property 'stop' of undefined or null reference

**Comment by Gix075** [comment]
Give me some more info. I tested it on IE11 and works for me. 
Which version of IE you are testing?
Which plugin animation are you using?

**Comment by tanveer12332** [comment]
i m using jQueryIntroLoader - v1.6.0 and my IE version is 11.0.96 and 11.26 and save issue in Edge

**Comment by Gix075** [comment]
Hi I tested v 1.7.1 in Explorer 11 and Edge and it works, including start and stop method. Have you a public link where I can see your page?

**Comment by tanveer12332** [comment]
yes see my projdect www.cloud.mybusinessmanager.com and open developers toolbar and see inline introloader function

**Comment by Gix075** [comment]
At now i can see that your page works on my IE11 and Edge.<br>

> Unable to get property 'stop' of undefined or null reference

Reading your code I'm seeing that you tried to stop plugin (at now is commented on your code) where plugin does not exists. This happens because you launch plugin only if *window.localStorage.getItem('user')* is *null*, and if not you try to stop plugin. For this reason you received the error message. <br>Read my comment on your code:

```javascript
if (window.localStorage.getItem('user') == null) {
    $("#element").introLoader({
        [...]
    });
    // here plugin exists and you can use .stop() method
    var loader = $('#element').data('introLoader');
    loader.stop(); // this will work
} else {
    // here plugin NOT exists and you can't use .stop() method
    var loader = $('#element').data('introLoader');
    loader.stop(); // this will not work
}
```

So i think that the correct way to use this plugin in your scenario is to do exactly what you have done or something similar (not tested):
```javascript
if (window.localStorage.getItem('user') == null) {
    $('body').append('<div id="element"></div>');
    $("#element").introLoader({
        [...]
    });
}
```
I hope that this can be helpuf.

**Comment by tanveer12332** [comment]
yes is working thanks
